name: GitHub Actions Demo
on: [push]
jobs:
  test-deploy:
    runs-on: self-hosted
    steps:
      - name: Install dependencies
        run: yarn install
      - name: Pm2 list processes
        run: pm2 l
