name: GitHub Actions Demo
on: [push]
jobs:
  test-deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: CD
        run: cd ${{ github.workspace }}
      - name: Install dependencies
        run: yarn install
      - name: List files
        run: ls .
      - name: Start app
        run: pm2 start pm2-dev.json
      - name: Pm2 list processes
        run: pm2 l
